/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GameRouteImport } from './routes/game'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConclusaoRouteImport } from './routes/conclusao'
import { Route as IndexRouteImport } from './routes/index'

const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusaoRoute = ConclusaoRouteImport.update({
  id: '/conclusao',
  path: '/conclusao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conclusao': typeof ConclusaoRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/progresso': typeof ProgressoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conclusao': typeof ConclusaoRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/progresso': typeof ProgressoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conclusao': typeof ConclusaoRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/progresso': typeof ProgressoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conclusao'
    | '/dashboard'
    | '/game'
    | '/login'
    | '/onboarding'
    | '/progresso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conclusao'
    | '/dashboard'
    | '/game'
    | '/login'
    | '/onboarding'
    | '/progresso'
  id:
    | '__root__'
    | '/'
    | '/conclusao'
    | '/dashboard'
    | '/game'
    | '/login'
    | '/onboarding'
    | '/progresso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConclusaoRoute: typeof ConclusaoRoute
  DashboardRoute: typeof DashboardRoute
  GameRoute: typeof GameRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgressoRoute: typeof ProgressoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusao': {
      id: '/conclusao'
      path: '/conclusao'
      fullPath: '/conclusao'
      preLoaderRoute: typeof ConclusaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConclusaoRoute: ConclusaoRoute,
  DashboardRoute: DashboardRoute,
  GameRoute: GameRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProgressoRoute: ProgressoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
